default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: pro
  password:
  host: 127.0.0.1

development:
  <<: *default
  database: meetapp_development

test:
  <<: *default
  database: meetapp_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: meetapp
