name: Testing

on:
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.7.1]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Cache project dependencies
        uses: actions/cache@v2
        with:
#          path: vendor/bundle
          path: vendor/
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev
      - name: Check if postgres is ready
        run: |
          echo '****************'
          pg_isready -h localhost -p 5432
          whoami
          echo '****************'
      - name: Install project dependencies
        run: |
          gem install bundler
          bundle install --path='vendor/bundle' --jobs 4 --retry 3
      - name: Set up db
        env:
          RAILS_ENV: test
#          POSTGRES_HOST: 127.0.0.1
#          POSTGRES_PORT: 5432
#          PGHOST: localhost
        run: |
          echo '****************'
          echo ${RAILS_ENV}
          echo ${POSTGRES_HOST}
          echo ${POSTGRES_PORT}
          pg_isready -h localhost -p 5432
          echo '****************'
          bundle exec rails db:setup
      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          make test
